OWNER_NAME="KËNÄN"
PREFIX=":"
PUBLIC_MODE='oui'
AUTO_READ_STATUS="oui"
AUTO_DOWNLOAD_STATUS="non"
BOT_NAME= "DARK KËNÄN"
IMAGE_MENU= "https://telegra.ph/file/835c3a335c8e2585898fc.jpg"
NUMERO_OWNER= "243972681974"
OWNER_NAME= "KËNÄN"
DATABASE_URL= "postgresql://hacking_database_q4zj_user:CuF96cXla7yH23fDrGsHFrKQa2e0Tog6@dpg-cqjo9ruehbks73cf84mg-a.oregon-postgres.render.com/hacking_database_q4zj"
WARN_COUNT= ""
OPENAI_API_KEY= ""
STARTING_BOT_MESSAGE='yes'
ANTI_DELETE_MESSAGE='yes'
